services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    init: true
    environment:
      # Set the user and group IDs for the container user.
      # This helps avoid permission issues with mounted volumes.
      # Find your user's ID with `id -u` and group ID with `id -g`.
      - PUID=10001
      - PGID=10001
    env_file:
      - .env
    volumes:
      - paperless-gpt-config:/app/config
      - paperless-gpt-db:/app/db
      - paperless-gpt-prompts:/app/prompts
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - node_modules/
            - .git/

volumes:
  paperless-gpt-config:
  paperless-gpt-db:
  paperless-gpt-prompts:
